name: Build
on:
    workflow_call:
        secrets:
            DATABASE_URL:
                description: The database connection URL.
                required: false
            COOKIE_SIGNING_SECRET:
                description: The secret to sign cookies with
                required: false
            ENCRYPTION_KEY:
                description: The key used to encrypt to private key, which itself is used for signing JWTs
                required: false
            EMAIL_USER:
                description: The username of the user of the email service.
                required: false
            EMAIL_PASSWORD:
                description: The password of the user for the email service.
                required: false
env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    COOKIE_SIGNING_SECRET: ${{ secrets.COOKIE_SIGNING_SECRET }}
    ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
    EMAIL_USER: ${{ secrets.EMAIL_USER }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    NX_NATIVE_COMMAND_RUNNER: false
jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: dnd-mapp/actions/setup-node@main
            - name: Install dependencies
              run: npm ci
            - name: Check linting
              run: npm run lint
            - name: Check formatting
              run: npm run format:check
            - name: Compile code
              run: npm run build
            - name: Run tests
              run: npm run test
